export const Emojis: Record<string, string> = {
    Anxious: '😰',
    Apathetic: '😐',
    Tired: '😫',
    Happy: '😊',
    Sad: '😢',
    Angry: '😠',
    Calm: '😌',
    Excited: '🤩',
    ExtremelyCold: '🥶',
    Cold: '😬',
    Pleasant: '😊',
    Hot: '😓',
    ExtremelyHot: '🥵',
    Yes: '✅',
    No: '❌',
    VeryBad: '😵',
    Bad: '😪',
    Good: '😴',
    VeryGood: '🛌',
};