name: Build and package backend

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Setup .NET SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      # Step 3: Restore EF Core CLI Tools locally
      - name: Install EF Core CLI Tools locally
        run: |
          cd backend
          dotnet tool restore

      # Step 4: Restore Dependencies
      - name: Restore Dependencies
        run: |
          cd backend
          dotnet restore

      # Step 5: Generate Migration SQL Script
      - name: Generate Migration SQL Script
        run: |
          cd backend
          echo "DatabaseConnectionString=${{ secrets.DATABASE_CONNECTION_STRING }}" >> $GITHUB_ENV
          dotnet ef migrations script -o publish/migration.sql

      # Step 6: Build the Application
      - name: Build the Application
        run: |
          cd backend
          dotnet publish -c Release -o publish

      # Step 7: Package the Application
      - name: Package the Application
        run: |
          cd backend/publish
          zip -r ../lifejournaler-backend.zip .

      # Step 8: Upload Package as Artifact
      - name: Upload Package as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: lifejournaler-backend
          path: backend/lifejournaler-backend.zip
